openapi: 3.0.0
info:
  title: Product API
  version: "1.0.0"
paths:
  /products:
    get:
      summary: Retrieve all products
      responses:
        '200':
          description: A list of products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Create a new product
      requestBody:
        description: Product to create.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /products/{id}:
    parameters:
      - name: id
        in: path
        description: The unique identifier of the product.
        required: true
        schema:
          type: integer
    get:
      summary: Retrieve product by ID
      responses:
        '200':
          description: Product retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    put:
      summary: Update product by ID
      requestBody:
        description: Product with updated data.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Product updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    delete:
      summary: Delete product by ID
      responses:
        '204':
          description: Product deleted successfully.
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          description: The product identifier.
        name:
          type: string
          description: The name of the product.
        description:
          type: string
          description: A short description of the product.
        price:
          type: number
          format: double
          description: The price of the product.
      required:
        - name
        - price